#!/usr/bin/env python3
# Generates routers/api/v1/openapi_routes_gen.go: one oapi.Route literal per
# operation, mechanically converted from the verified route table. The rows
# are keyed by operationId and looked up when the handler is registered, so
# routing and the spec share one artifact.
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TABLE = REPO / "contrib" / "openapi-port" / "out" / "route-table.json"
OUT = REPO / "routers" / "api" / "v1" / "openapi_routes_gen.go"

HEADER = """// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

// Code generated by contrib/openapi-port/gen_routes_doc.py; DO NOT EDIT.

package v1

import (
	activities_model "gitea.dev/models/activities"
	api "gitea.dev/modules/structs"
	oapi "gitea.dev/modules/openapi"
	forms "gitea.dev/services/forms"
)

// openAPIRoutes returns the API's documentation rows: method, pattern and
// documentation per operation in one literal. Together with the registrations
// in Routes(), these rows are the API contract; the spec is a projection of
// them (ADR 0001).
func openAPIRoutes() []oapi.Route {
	return []oapi.Route{
"""

# definition name -> fully qualified Go type expression
PACKAGE_BY_DEF = {}

def qual_type(name):
    """Return a Go type expression for a swagger definition name."""
    pkg = PACKAGE_BY_DEF.get(name)
    if pkg == "gitea.dev/services/forms":
        # go-swagger carried one forms type under a spec-specific name
        return "forms.MergePullRequestForm" if name == "MergePullRequestOption" else "forms." + name
    if pkg == "gitea.dev/models/activities":
        return "activities_model." + name
    return "api." + name

response_error_names = {"error", "notFound", "forbidden", "unauthorized", "validationError", "conflict", "empty", "repoArchivedError", "invalidTopicsError"}

def go_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

def go_schema_type(t, fmt):
    if fmt == "int64": return "int64"
    return {"string": "string", "integer": "int64", "boolean": "bool"}.get(t, t)

def go_param(p):
    parts = [f'Name: {go_str(p["name"])}', f'In: {go_str(p.get("in", "query"))}']
    if p.get("description"): parts.append(f'Description: {go_str(p["description"])}')
    if p.get("required"): parts.append("Required: true")
    if p.get("type"): parts.append(f'Type: {go_str(p.get("type"))}')
    if p.get("format"): parts.append(f'Format: {go_str(p.get("format"))}')
    if p.get("enum"):
        vals = ", ".join(go_str(v) for v in p["enum"])
        parts.append(f'Enum: []string{{{vals}}}')
    if p.get("default") is not None:
        dv = p["default"]
        if isinstance(dv, bool): parts.append(f'Default: {str(dv).lower()}')
        elif isinstance(dv, (int, float)): parts.append(f'Default: {dv}')
        else: parts.append(f'Default: {go_str(str(dv))}')
    return "oapi.Param{" + ", ".join(parts) + "}"

def response_for(ref):
    # map the swagger:response name to (description, schema expr)
    if ref in response_error_names:
        return None  # handled by shared error constructors
    return ref

def go_route(row):
    fields = [f'OperationID: {go_str(row["operationId"])}', f'Method: {go_str(row["method"])}', f'Pattern: {go_str(row["path"])}', f'Summary: {go_str(row["summary"])}', f'Tags: []string{{{go_str(row["tag"])}}}']
    params = [go_param(p) for p in row.get("parameters", []) if p.get("in") != "body"]
    body_params = [p for p in row.get("parameters", []) if p.get("in") == "body"]
    if body_params:
        schema_ref = body_params[0].get("schema", {}).get("$ref", "")
        typ = schema_ref.split("/")[-1]
        fields.append('Body: &oapi.RequestBody{Schema: ' + qual_type(typ) + '{}}')
    if params:
        fields.append("Params: []oapi.Param{" + ",\n".join(params) + "}")
    resps = []
    for code, r in sorted(row.get("responses", {}).items()):
        ref = r.get("$ref") if isinstance(r, dict) else None
        desc = r.get("description") if isinstance(r, dict) else None
        if ref == "empty":
            resps.append(f'{code}: {{Description: "success"}}')
        elif ref in response_error_names:
            resps.append(f'{code}: {{Description: {go_str(_sw2["responses"][ref].get("description", ref))}}}')
        elif ref and not desc:
            sdesc, schema = response_schema(ref)
            if schema:
                resps.append(f'{code}: {{Description: {go_str(sdesc)}, Schema: {schema}}}')
            else:
                resps.append(f'{code}: {{Description: {go_str(sdesc)}}}')
        elif desc:
            resps.append(f'{code}: {{Description: {go_str(desc)}}}')
        elif ref:
            sdesc, schema = response_schema(ref)
            resps.append(f'{code}: {{Description: {go_str(sdesc)}, Schema: {schema}}}' if schema else f'{code}: {{Description: {go_str(sdesc)}}}')
    if resps:
        fields.append("Responses: map[int]oapi.Response{\n" + ",\n".join(" " * 3 + r for r in resps) + ",\n  }")
    lit = "oapi.Route{\n"
    for f in fields:
        lit += " " * 3 + f + ",\n"
    lit += " }"
    return lit

def error_description(name):
    return _sw2["responses"][name].get("description", name)

def response_schema(ref):
    # ref is a swagger:response name; resolve to (description, schema go expr)
    import json as _json
    global _sw2
    r = _sw2["responses"].get(ref)
    if not r:
        return ref, None
    desc = r.get("description", "")
    s = r.get("schema", {})
    if "$ref" in s:
        return desc, qual_type(s["$ref"].split("/")[-1]) + "{}"
    if s.get("type") == "array":
        item = s.get("items", {})
        if "$ref" in item:
            return desc, "[]" + qual_type(item["$ref"].split("/")[-1]) + "{}"
        return desc, "[]string{}"
    if s.get("type") == "object":
        return desc, "map[string]int64{}"
    if s.get("type") == "string":
        return desc, "string{}"
    return desc, None

def main():
    global _sw2
    _sw2 = json.loads((REPO / "templates" / "swagger" / "v1-swagger.generated.json").read_text())
    for name, defn in _sw2["definitions"].items():
        PACKAGE_BY_DEF[name] = defn.get("x-go-package", "gitea.dev/modules/structs")
    rows = json.loads(TABLE.read_text())
    parts = [HEADER]
    for row in rows:
        parts.append(f'\t\t{go_route(row)},\n')
    parts.append("\t}\n}\n")
    OUT.write_text("".join(parts))
    print(f"wrote {OUT} ({len(rows)} rows)")

if __name__ == "__main__":
    main()
